Camera editor sensor
RobotecAI/o3de-ros2-gem pull request #321
Opened 2022-11-18 20:05 UTC by michalpelka

2022-11-22 17:45 UTC, michalpelka commented
Tested against:
o3de : cb09e08b75e66c509e80e6f17a9981928b8d3a59
RosConDemo: 6922187247b0b23e4bb91fd1fba09060b42ab76c

2022-11-23 11:52 UTC, pawelbudziszewski requested changes

2022-11-23 11:52 UTC, pawelbudziszewski commented on Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
> +            Internal::MakeTopicConfigurationPair("camera_image_color", Internal::kImageMessageType, Internal::kColorImageConfig));
I've got a compilation error:
`error: use of undeclared identifier 'Internal'`

2022-11-23 11:52 UTC, pawelbudziszewski commented on Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
> +    }
...and for all other `Internal`-s in this part

2022-11-23 12:37 UTC, pawelbudziszewski commented
Is there any particular reason why this camera is created along the Z-axis? The O3DE camera is always looking along the Y-axis. It might be helpful while setting the ROS camera if it was rotated in the same way as the O3DE cam.

![Screenshot from 2022-11-23 13-24-58](https://user-images.githubusercontent.com/31925544/203548493-ab1d0b78-4269-4d7e-ab99-df5e7f70b0a0.png)

2022-11-23 13:15 UTC, michalpelka commented
Yes, there is a very particular reason and it is  - it is an image processing coordinate system. O3de uses more entertainment industry standards for camera coordinate.

Here is a quote from [REP-103:](https://www.ros.org/reps/rep-0103.html#id22)

```
In the case of cameras, there is often a second frame defined with a "_optical" suffix. This uses a slightly different convention:

    z forward
    x right
    y down
```    
I will defend this coordinate system - as an essential thing here. What is more, there is no easy way to implement what you mentioned @pawelbudziszewski  - note that the camera needs a **Ros2SensorComponent** - and the **Ros2SensorComponent** is not aware if it is part of the camera or not.
Implementing such a "quirk" would result in a number of unnecessary discrepancies, that would render the whole component unusable.  That tool is intended for ROS2 users - that community would appreciate that we are using well-established standards.

2022-11-23 15:09 UTC, pawelbudziszewski requested changes

2022-11-23 15:09 UTC, pawelbudziszewski commented on Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
> +        AZ::Transform transform = GetEntity()->GetTransform()->GetWorldTM();
Compilation error:

`o3de-ros2-gem/Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp:96:62: error: member access into incomplete type 'AZ::TransformInterface'`

Including `AzCore/Component/TransformBus.h` resolves the problem

2022-11-23 15:15 UTC, michalpelka commented on Code/Source/Camera/ROS2CameraSensorEditorComponent.cpp
> +        AZ::Transform transform = GetEntity()->GetTransform()->GetWorldTM();
Done

2022-11-23 15:42 UTC, pawelbudziszewski approved these changes
Works fine now. I have no further comments.

Tested:
- All parameters seem to work correctly, in particular:
- FOV seems to be set correctly (at least images look similar to the O3DE cam image)
- Depth camera values seem reasonable
- All data can be accessed via ROS topics

As for the camera rotation: I accept the explanation.

2022-11-30 15:49 UTC, adamdbrw commented
This is a very useful PR. I would love this to connect with Visualise() of ROS2SensorComponent.

Visualise could be different for Editor and Game mode components (for example, lidar as frustum vs as points). Perhaps there should be a ROS2SensorEditorComponent?

2023-01-16 10:26 UTC, michalpelka commented
This PR will be moved to https://github.com/o3de/o3de-extras/

2023-01-16 10:26 UTC, closed without merging